name: Java Library Template CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Trigger the worflow on push or pull request by only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-java-template:
    runs-on: ubuntu-20.04
    container:
      image: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-vineyard:latest
      options:
        --shm-size 4096m
    steps:
    - uses: actions/checkout@v2.3.2

    - name: Install graphscope
      env:
        GS_CODE_HOME : ${{ github.workspace }}/GraphScope
      run: |
        git clone -b main --single-branch https://github.com/alibaba/GraphScope.git ${GS_CODE_HOME}
        cd  ${GS_CODE_HOME}
        # default install to "/opt/graphscope"
        make gae ENABLE_JAVA_SDK=ON
        # also make coordinator and client for python test
        make coordinator && make client

    - name : Build
      run : |
        mvn clean install


    - name: Run Test
      env:
        GRAPHSCOPE_HOME: /opt/graphscope
      run: |
        mvn exec::exec@python
